/** A single subtitle entry. Times are in seconds (float). */
export interface Cue {
  /** Stable id used as a React key and for editing. */
  id: string
  /** Start time in seconds. */
  start: number
  /** End time in seconds. */
  end: number
  /** Cue text. May contain newlines for multi-line cues. */
  text: string
}

/** Where a track's cues came from — drives labelling and UX hints. */
export type SubtitleOrigin =
  | 'embedded' // extracted from a track inside the source file
  | 'whisper' // transcribed from audio with Whisper
  | 'caption' // generated by describing video frames
  | 'imported' // user dropped in an .srt/.vtt file
  | 'manual' // created from scratch in the editor

export interface SubtitleTrack {
  id: string
  /** Human-readable label shown in the UI, e.g. "English (Whisper)". */
  label: string
  /** BCP-47 / ISO code when known, e.g. "en". */
  language?: string
  origin: SubtitleOrigin
  cues: Cue[]
}

/** Generate a unique id for a cue or track. */
export function uid(prefix = 'id'): string {
  if (typeof crypto !== 'undefined' && 'randomUUID' in crypto) {
    return `${prefix}_${crypto.randomUUID()}`
  }
  // Fallback for older runtimes / workers without crypto.randomUUID.
  return `${prefix}_${Math.abs(hashString(`${prefix}${performance.now()}`)).toString(36)}`
}

function hashString(s: string): number {
  let h = 0
  for (let i = 0; i < s.length; i++) {
    h = (Math.imul(31, h) + s.charCodeAt(i)) | 0
  }
  return h
}

/** Return cues sorted by start time (does not mutate the input). */
export function sortCues(cues: Cue[]): Cue[] {
  return [...cues].sort((a, b) => a.start - b.start || a.end - b.end)
}

/** The cue active at a given playback time, if any. */
export function cueAt(cues: Cue[], time: number): Cue | undefined {
  return cues.find((c) => time >= c.start && time < c.end)
}
